Repository FRONTENDSCHOOL8/find-it, pull requests merged in 2024-02, with the labels that each got.

#7 [환경] (jung/#06) 아이콘 추출
  src/assets/icons/icon_bell.svg
  src/assets/icons/icon_bookmarkt_18.svg
  src/assets/icons/icon_check.svg
  src/assets/icons/icon_doc.svg
  src/assets/icons/icon_envelope.svg
  src/assets/icons/icon_search_16.svg
Labels: env

#12 [환경] 기본 에셋 공통 아이콘 추출 완료
  src/assets/components/SignIn/SignIn.tsx
  src/assets/icons/icon_ accordion_down.svg
  src/assets/icons/icon_ accordion_up.svg
  src/assets/icons/icon_add.svg
  src/assets/icons/icon_bullet.svg
  src/assets/icons/icon_calendar.svg
  src/assets/icons/icon_camera.svg
  src/assets/icons/icon_comment.svg
  src/assets/icons/icon_confirm.svg
  src/assets/icons/icon_delete.svg
  src/assets/icons/icon_exit.svg
  src/assets/icons/icon_eye_off.svg
  src/assets/icons/icon_eye_on.svg
  src/assets/icons/icon_like_fill.svg
  src/assets/icons/icon_like_stroke.svg
  src/assets/icons/icon_my_bookmark_fill.svg
  src/assets/icons/icon_my_bookmark_none.svg
  src/assets/icons/icon_next.svg
  src/assets/icons/icon_next_14.svg
  src/assets/icons/icon_pencil.svg
  src/assets/icons/icon_prev.svg
  src/assets/icons/icon_right.svg
  src/assets/icons/icon_search.svg
  src/assets/icons/icon_search_36.svg
Labels: env

#13 [기능] Navigation 컴포넌트 마크업 및 스타일링
  .storybook/preview.ts
  package.json
  pnpm-lock.yaml
  src/assets/icons/LOGOTYPE_false.svg
  src/assets/icons/LOGOTYPE_small_false.svg
  src/assets/icons/LOGOTYPE_small_true.svg
  src/assets/icons/LOGOTYPE_true.svg
  src/assets/icons/LOGO_SYMBOL.svg
  src/assets/navigation/icon_board_false.svg
  src/assets/navigation/icon_board_true.svg
  src/assets/navigation/icon_box_false.svg
  src/assets/navigation/icon_box_true.svg
  src/assets/navigation/icon_home_false.svg
  src/assets/navigation/icon_home_true.svg
  src/assets/navigation/icon_lost_false.svg
  src/assets/navigation/icon_lost_true.svg
  src/assets/navigation/icon_profile_false.svg
  src/assets/navigation/icon_profile_true.svg
  src/components/Navigation/Navigation.stories.tsx
  src/components/Navigation/Navigation.tsx
  src/components/Navigation/NavigationItem/NavigationItem.stories.tsx
  src/components/Navigation/NavigationItem/NavigationItem.tsx
  tailwind.config.js
Labels: feature

#18 [기능] 로그인 마크업 기본 완료 및 테일윈드 설정 수정
  src/App.tsx
  src/assets/components/SignIn/SignIn.tsx
  src/components/SignIn/SignIn.tsx
  src/components/SignIn/color.css
  src/components/SignIn/icons/IconDelete.tsx
  src/components/SignIn/icons/IconEye.tsx
  tailwind.config.js
Labels: feature

#19 [기능] Header 컴포넌트 마크업 및 스타일링
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/components/Header/Header.stories.tsx
  src/components/Header/Header.tsx
Labels: feature

#21 [기능] 로그인 마크업 & 버튼 베리어블 컴포넌트 분리
  src/components/SignIn/SignIn.tsx
  src/components/SignIn/atom/AlertText.tsx
  src/components/SignIn/atom/ButtonDoubleCheck.tsx
  src/components/SignIn/atom/IconDelete.tsx
  src/components/SignIn/atom/IconEyeOff.tsx
  src/components/SignIn/atom/IconEyeOn.tsx
  src/components/SignIn/color.css
  src/components/SignIn/icons/IconDelete.tsx
  src/components/SignIn/icons/IconEye.tsx
  src/components/SignIn/molecules/ButtonIcon.stories.tsx
  src/components/SignIn/molecules/ButtonIcon.tsx
  src/components/SignIn/molecules/ButtonVariable.tsx
  src/components/SignIn/molecules/InputForm.tsx
Labels: feature

#24 [리팩토링] 로그인 컴포넌트 분리
  src/components/ItemBox.tsx
  src/components/SignIn/SignIn.tsx
  src/components/SignIn/molecule/ButtonIcon.tsx
  src/components/SignIn/molecule/InputForm.tsx
  src/components/SignIn/molecules/ButtonIcon.stories.tsx
  src/components/SignIn/molecules/ButtonIcon.tsx
  src/components/common/atom/IconDelete.tsx
  src/components/common/molecule/ButtonVariable.tsx
Labels: refactoring, etc

#26 [기능] Modal 컴포넌트 마크업 및 스타일링
  src/components/common/molecule/Modal.stories.tsx
  src/components/common/molecule/Modal.tsx
Labels: feature

#28 [코드 수정] Header 컴포넌트 스타일링 수정
  src/components/Header/Header.tsx
Labels: mod

#29 [기능] Splash 및 메인페이지 마크업 및 스타일링
  src/App.tsx
  src/assets/logo.svg
  src/components/ItemBox/ItemBox.tsx
  src/components/pages/Main.tsx
  src/components/pages/Splash.tsx
Labels: feature

#38 [기능] 카테고리 (대/소분류 or 행정구역 선택용) 모달 마크업 완료
  src/components/SignIn/SignIn.tsx
  src/components/common/molecule/SelectCategoryList.tsx
  src/components/common/molecule/SelectLocalList.tsx
Labels: feature

#39 [환경](jung/#37) 전역변수용컬러값 css파일 추가
  src/App.tsx
  src/components/SignIn/SignIn.tsx
  src/components/SignIn/molecule/InputForm.tsx
  src/components/common/atom/AlertText.tsx
  src/components/common/pages/Main.tsx
  src/components/common/pages/Splash.tsx
  src/style.css
Labels: env

#46 [기능] (kim/#43): Horizon(구분선) 컴포넌트 마크업 및 스타일링
  src/components/Header/Header.tsx
  src/components/SearchDetail/molecule/SearchDate.stories.tsx
  src/components/SearchDetail/molecule/SearchDate.tsx
  src/components/SearchDetail/pages/SearchDetail.stories.tsx
  src/components/SearchDetail/pages/SearchDetail.tsx
  src/components/common/atom/Horizon.stories.tsx
  src/components/common/atom/Horizon.tsx
  src/tailwind.css
Labels: feature

#52 [기능] (kim/#31): SearchDetail(상세검색) 컴포넌트 마크업 및 스타일링
  src/assets/search/select.svg
  src/components/SearchDetail/atom/SearchParagraph.stories.tsx
  src/components/SearchDetail/atom/SearchParagraph.tsx
  src/components/SearchDetail/molecule/SearchDate.tsx
  src/components/SearchDetail/pages/SearchDetail.tsx
Labels: feature
