Repository FRONTENDSCHOOL8/find-it, pull requests merged in 2024-03, with the labels that each got.

#53 [기능] 마이페이지(메인) 마크업 및 스타일링
  src/assets/icons/icon_bookmark.svg
  src/assets/icons/icon_docs.svg
  src/assets/profile.svg
  src/components/pages/MyPage.tsx
  src/lib/utils/getPbImgURL.tsx
Labels: feature

#55 [기능] (cho/#54) Credit 페이지 마크업 및 스타일링
  src/components/pages/Credit.tsx
Labels: feature

#56 [기능] 지역 리스트 api 랜더 구현
  src/App.tsx
  src/components/SignIn/atom/AlertText.tsx
  src/components/SignIn/atom/ButtonDoubleCheck.tsx
  src/components/SignIn/atom/IconEyeOff.tsx
  src/components/SignIn/atom/IconEyeOn.tsx
  src/components/SignIn/molecule/ButtonIcon.tsx
  src/components/SignIn/molecule/GetLocalList.tsx
  src/components/SignIn/molecule/InputForm.stories.tsx
  src/components/SignIn/molecule/InputForm.tsx
  src/components/SignIn/pages/SignIn.tsx
  src/components/SignIn/셀릭스티르스 테스트.tsx
  src/components/common/atom/AlertText.tsx
  src/components/common/molecule/ButtonVariable.tsx
  src/components/common/molecule/SelectCategoryList.tsx
Labels: feature

#59 [기능] (cho/#58) 메인페이지 ItemBox 스와이퍼 적용
  package.json
  pnpm-lock.yaml
  src/components/ItemBox/ItemBox.tsx
  src/components/ItemBox/SwiperItem.tsx
  src/components/pages/Main.tsx
  src/tailwind.css
Labels: feature

#68 [기능] (kim/#67): SearchResult 컴포넌트 마크업 및 스타일링
  .eslintrc.cjs
  src/components/SearchDetail/pages/SearchDetail.tsx
  src/components/SearchResult/SearchResult.stories.tsx
  src/components/SearchResult/SearchResult.tsx
Labels: feature

#70 [코드수정] 회원가입 기능 추가(중복확인, 지역 외 완료)
  src/App.tsx
  src/components/SignIn/molecule/InputForm.tsx
  src/components/common/atom/AlertText.tsx
  src/components/pages/SignIn.tsx
  src/components/pages/SignUp.tsx
Labels: mod, feature

#71 [기능] (kim/#69): tawk.to를 사용한 관리자와의 채팅 기능 구현
  src/components/pages/MyPage.tsx
Labels: feature

#75 [코드 수정] (Kim/#74): Header, Navigation, SearchResult 컴포넌트 스타일링 수정
  src/components/Header/Header.tsx
  src/components/Navigation/Navigation.tsx
  src/components/SearchResult/SearchResult.tsx
Labels: mod

#79 [기능] (kim/#76): Navagition 영역 Main, MyPage Link 연결
  src/components/Navigation/NavigationItem/NavigationItem.tsx
Labels: feature

#81 [코드수정] (cho/#78) 크레딧, 마이페이지 코드 수정
  src/components/pages/Credit.tsx
  src/components/pages/MyPage.tsx
Labels: mod

#84 [코드 수정] (Kim/#80): 상세검색 페이지 습득물, 분실물 분할
  src/App.tsx
  src/components/SearchDetail/pages/SearchFindDetail.stories.tsx
  src/components/SearchDetail/pages/SearchFindDetail.tsx
  src/components/SearchDetail/pages/SearchLostDetail.stories.tsx
  src/components/SearchDetail/pages/SearchLostDetail.tsx
Labels: mod

#85 [코드수정] signup 수정
  src/App.tsx
  src/assets/img_welcome.png
  src/components/SignIn/molecule/InputForm.tsx
  src/components/SignIn/molecule/InputIconButton.tsx
  src/components/common/atom/AlertText.tsx
  src/components/common/molecule/ButtonVariable.tsx
  src/components/pages/SignIn.tsx
  src/components/pages/SignUp.tsx
  src/components/pages/Welcome.tsx
  src/components/pages/index.ts
Labels: mod

#88 [코드수정] 회원가입 기능 전체 완료
  src/App.tsx
  src/components/SignIn/atom/IconDoubleCheck.tsx
  src/components/SignIn/molecule/GetLocalList.tsx
  src/components/SignIn/molecule/InputIconButton.tsx
  src/components/common/molecule/ButtonSelectItem.tsx
  src/components/common/molecule/SelectCategoryList.tsx
  src/components/pages/SignUp.tsx
  src/lib/utils/useGetToken.tsx
Labels: mod, feature

#90 [기능] 로그인 페이지 구현 완료
  src/components/common/molecule/ButtonVariable.tsx
  src/components/pages/SignIn.tsx
  src/components/pages/SignUp.tsx
  src/lib/utils/useGetToken.tsx
Labels: mod, feature

#93 [기능]로그인 유저정보 동기화
  src/App.tsx
  src/components/Navigation/Navigation.tsx
  src/components/Navigation/NavigationItem/NavigationItem.tsx
  src/components/pages/Main.tsx
  src/components/pages/MyPage.tsx
  src/components/pages/MypageEntry.tsx
  src/components/pages/SignIn.tsx
  src/components/pages/SignUp.tsx
  src/components/pages/Welcome.tsx
  src/components/pages/index.ts
  src/lib/utils/getPbImgURL.tsx
Labels: mod

#95 [기능](jung/#94) 공지사항 페이지 추가
  src/App.tsx
  src/components/Notice/Icons.tsx
  src/components/Notice/NoticeItem.tsx
  src/components/pages/MyPage.tsx
  src/components/pages/Notice.tsx
  src/components/pages/index.ts
Labels: feature

#96 [기능] (cho/#62) 습득물 게시판 렌더링
  src/assets/loading.svg
  src/components/ItemBox/ItemBox.tsx
  src/components/pages/GetList.tsx
  tsconfig.json
Labels: feature

#99 [기능/코드 수정] (Kim/#87): 배포 전 검색 기능 중간 PR
  src/App.tsx
  src/components/SearchDetail/molecule/SearchDate.tsx
  src/components/SearchDetail/pages/SearchFindDetail.tsx
  src/components/SearchResult/SearchResult.tsx
Labels: mod, feature

#101 [버그수정] (cho/#62) ItemBox 컴포넌트 타입 오류 수정
  src/components/ItemBox/ItemBox.tsx
Labels: bugfix

#100 [코드수정](jung/#98) 네비게이션 링크 추가
  src/App.tsx
  src/components/Navigation/NavigationItem/NavigationItem.tsx
  src/components/pages/index.ts
Labels: mod

#103 [코드 수정] (kim/#87): 배포 충돌 수정
  src/App.tsx
  src/components/SearchDetail/pages/SearchFindDetail.tsx
  src/components/SearchDetail/pages/SearchLostDetail.stories.tsx
  src/components/SearchDetail/pages/SearchLostDetail.tsx
Labels: bugfix, mod

#104 [버그 픽스]Jung/#102 배포 충돌 수정
  src/components/pages/MyPage.tsx
  src/store/detail/detailData.ts
Labels: bugfix

#106 [버그수정] SwiperItem, GetList 버그 수정
  src/components/ItemBox/ItemBox.tsx
  src/components/pages/GetList.tsx
  src/lib/utils/getAPIData.ts
Labels: bugfix

#114 [환경](jung/#113) pages 폴더 트리 정리
  src/App.tsx
  src/assets/missingbox.svg
  src/components/pages/01-Main/Main.tsx
  src/components/pages/01-Main/NotFound.tsx
  src/components/pages/01-Main/Splash.tsx
  src/components/pages/02-FindItem/GetDetail.tsx
  src/components/pages/02-FindItem/GetList.tsx
  src/components/pages/04-MyPage/Credit.tsx
  src/components/pages/04-MyPage/MyPage.tsx
  src/components/pages/04-MyPage/MypageDelete.tsx
  src/components/pages/04-MyPage/MypageEdit.tsx
  src/components/pages/04-MyPage/MypageEntry.tsx
  src/components/pages/04-MyPage/Notice.tsx
  src/components/pages/04-MyPage/SignIn.tsx
  src/components/pages/04-MyPage/SignUp.tsx
  src/components/pages/04-MyPage/Welcome.tsx
  src/components/pages/index.ts
Labels: env

#115 [코드수정](jung/#113) 회원정보 수정 완료
  src/components/Header/Header.tsx
  src/components/common/atom/AlertText.tsx
  src/components/pages/04-MyPage/MypageDelete.tsx
  src/components/pages/04-MyPage/MypageEdit.tsx
  src/components/pages/04-MyPage/SignIn.tsx
  src/components/pages/04-MyPage/SignUp.tsx
  src/components/pages/04-MyPage/Welcome.tsx
  src/lib/utils/useGetToken.tsx
Labels: mod

#123 [기능] 분실물명 검색, 분실물 상세 검색 함수 작성
  index.html
  src/components/Detail/Detail.tsx
  src/lib/utils/getAPIData.ts
  src/lib/utils/lostAPIData.ts
  src/store/detail/detailData.ts
  src/store/detail/useDetailData.ts
  vite.config.ts.timestamp-1709879298749-733b583765b35.mjs
Labels: doc, feature

#119 [코드수정] 각종 코드 수정
  src/App.tsx
  src/assets/itembox/default_item.svg
  src/components/ItemBox/ItemBox.tsx
  src/components/common/atom/GetTimeDiff.tsx
  src/components/pages/02-FindItem/GetList.tsx
  src/components/pages/03-LostItem/LostList.tsx
  src/components/pages/index.ts
Labels: mod, feature

#121 [코드수정] (cho/#78) getTimeDiff 함수 변경 및 적용
  src/components/pages/01-Main/Main.tsx
  src/lib/utils/getTimeDiff.tsx
Labels: mod

#127 [기능] 자유게시판(약식) 추가
  index.html
  public/favicon.svg
  src/App.tsx
  src/assets/icons/icon_plus.svg
  src/components/Community/CreateBodyText.tsx
  src/components/Community/CreatePost.tsx
  src/components/Community/PostBody.tsx
  src/components/Community/PostBox.tsx
  src/components/Navigation/NavigationItem/NavigationItem.tsx
  src/components/SignIn/UserBookmark.ts
  src/components/SignIn/molecule/GetLocalList.tsx
  src/components/pages/04-MyPage/MypageEdit.tsx
  src/components/pages/04-MyPage/Notice.tsx
  src/components/pages/04-MyPage/SignUp.tsx
  src/components/pages/05-Community/PostDetail.tsx
  src/components/pages/05-Community/PostList.tsx
  src/components/pages/index.ts
Labels: feature

#128 [기능, 코드수정] (cho/#126) 메인 물품 박스 렌더링 및 코드 수정
  src/App.tsx
  src/components/ItemBox/ItemBox.tsx
  src/components/ItemBox/SwiperItem.tsx
  src/components/pages/01-Main/Main.tsx
  src/components/pages/02-FindItem/GetList.tsx
  src/components/pages/03-LostItem/LostList.tsx
  src/components/pages/04-MyPage/MyPage.tsx
  src/components/pages/05-Notification/Notice.tsx
  src/components/pages/05-Notification/Notification.tsx
  src/components/pages/05-Notification/Setting.tsx
  src/components/pages/index.ts
Labels: mod, feature

#129 [코드수정] (cho/#78) 폴더 인덱스 중복 및 경로 이슈 수정
  src/components/Community/PostBody.tsx
  src/components/Community/PostBox.tsx
  src/components/Navigation/NavigationItem/NavigationItem.tsx
  src/components/pages/06-Notification/Notice.tsx
  src/components/pages/06-Notification/Notification.tsx
  src/components/pages/06-Notification/Setting.tsx
  src/components/pages/index.ts
Labels: bugfix, mod

#130 [코드수정](jung/#117) useGetToken 무한로딩 수정
  src/components/pages/04-MyPage/MypageEdit.tsx
  src/lib/utils/useGetToken.tsx
Labels: mod

#132 [기능] (Kim/#87): 습득물 상세검색 페이지 조건 검색 기능 추가
  src/components/SearchDetail/pages/SearchFindDetail.tsx
  src/components/SearchResult/SearchResult.tsx
  src/lib/utils/getAPIData.ts
  src/lib/utils/getFormattedDate.ts
  src/store/search/searchStore.ts
Labels: feature

#134 [버그수정] (kim/#133): tawk.to 채팅 서비스 계정 에러 해결 및 마이페이지 외 나타나는 오류 해결
  src/components/pages/04-MyPage/MyPage.tsx
Labels: bugfix

#138 [기능] 자유게시판 검색 기능 추가
  index.html
  src/App.tsx
  src/components/Community/CreateBodyText.tsx
  src/components/Community/CreatePost.tsx
  src/components/Community/PostBox.tsx
  src/components/Community/PostDetailBody.tsx
  src/components/Navigation/Navigation.tsx
  src/components/common/atom/Horizon.tsx
  src/components/common/molecule/Modal.tsx
  src/components/common/molecule/ModalComp.tsx
  src/components/common/molecule/SelectCategoryList.tsx
  src/components/pages/01-Main/Main.tsx
  src/components/pages/01-Main/Splash.tsx
  src/components/pages/04-MyPage/MypageDelete.tsx
  src/components/pages/04-MyPage/MypageEdit.tsx
  src/components/pages/04-MyPage/Welcome.tsx
  src/components/pages/05-Community/PostDetail.tsx
  src/components/pages/05-Community/PostList.tsx
  src/components/pages/05-Community/SearchPost.tsx
  src/components/pages/index.ts
Labels: feature

#135 [코드수정] 프로필 수정 및 탈퇴 완료 모달 적용
  src/components/Community/CreateBodyText.tsx
  src/components/Community/CreatePost.tsx
  src/components/Community/PostDetailBody.tsx
  src/components/Navigation/Navigation.tsx
  src/components/common/atom/Horizon.tsx
  src/components/common/molecule/Modal.tsx
  src/components/common/molecule/ModalComp.tsx
  src/components/common/molecule/SelectCategoryList.tsx
  src/components/pages/04-MyPage/MypageDelete.tsx
  src/components/pages/04-MyPage/MypageEdit.tsx
  src/components/pages/04-MyPage/Welcome.tsx
  src/components/pages/05-Community/PostDetail.tsx
  src/components/pages/05-Community/PostList.tsx
Labels: mod

#143 [코드수정](jung/#137) 일부페이지 가운데 정렬
  src/components/pages/01-Main/Main.tsx
  src/components/pages/02-FindItem/GetList.tsx
  src/components/pages/04-MyPage/MyPage.tsx
  src/components/pages/05-Community/PostList.tsx
Labels: mod

#146 [버그 수정] (kim/#136): Navigation 컴포넌트 레이아웃 깨짐 문제 해결
  src/components/Navigation/Navigation.tsx
  src/components/Navigation/NavigationItem/NavigationItem.tsx
Labels: bugfix

#152 [코드 수정] (kim/#151): Shortcut, Header 컴포넌트 a 태그 라우터 처리
  src/App.tsx
  src/components/Header/Header.tsx
  src/components/SearchDetail/pages/SearchFindDetail.tsx
  src/components/SearchResult/SearchFindResult.stories.tsx
  src/components/SearchResult/SearchFindResult.tsx
  src/components/Shortcut/Shortcut.tsx
Labels: mod

#154 [코드수정](jung/#150) 프로필 수정 페이지 코드수정
  src/App.tsx
  src/components/SignIn/UserBookmark.ts
  src/components/pages/04-MyPage/MypageEdit.tsx
Labels: mod

#156 [코드수정] jung/#155 자유게시판 스타일 & 검색 링크 수정
  src/App.tsx
  src/components/Community/PostBox.tsx
  src/components/Header/Header.tsx
  src/components/pages/05-Community/PostList.tsx
Labels: mod

#160 [기능] 분실물, 습득물 리스트에서 돋보기 아이콘 클릭 시 상세검색 페이지로 이동
  src/App.tsx
  src/components/Header/Header.tsx
  src/components/pages/02-FindItem/GetList.tsx
  src/components/pages/03-LostItem/LostList.tsx
  src/main.tsx
Labels: feature

#162 [기능, 코드수정] (kim/#161): Navigation 컴포넌트 현재 페이지에 맞게 색상 변경 기능 추가 및 일부 컴포넌트 라우터 연결
  src/components/Header/Header.tsx
  src/components/Navigation/Navigation.tsx
  src/components/pages/01-Main/Main.tsx
Labels: mod, feature

#163 [기능] 리액트 헬멧 메타데이터 추가
  package.json
  pnpm-lock.yaml
  public/img_og.jpg
  src/App.tsx
  src/components/Community/PostBox.tsx
  src/components/pages/04-MyPage/Credit.tsx
  src/components/pages/04-MyPage/Notice.tsx
  src/components/pages/05-Community/PostList.tsx
  src/components/pages/05-Community/SearchPost.tsx
Labels: feature

#168 [기능] (kim/#164): SwiperItem 컴포넌트 스와이퍼 스켈레톤 UI 적용
  package.json
  pnpm-lock.yaml
  src/components/ItemBox/Skeleton.tsx
  src/components/ItemBox/SwiperItem.tsx
Labels: feature

#169 [기능] (cho/#122) 알림 기능 구현
  src/components/pages/06-Notification/Notice.tsx
  src/components/pages/06-Notification/Notification.tsx
  src/components/pages/06-Notification/Setting.tsx
  src/types/types.ts
Labels: feature

#172 [코드수정] (kim/#171): getAPIData 불필요한 콘솔 삭제 및 습득물 검색 결과 Route path 수정
  src/App.tsx
  src/lib/utils/getAPIData.ts
Labels: mod

#173 [기능] (kim/#170): 검색 결과, 습득물 리스트, 분실물 리스트 컴포넌트 아이템 초기 렌더링 시 Skeleton UI 적용
  src/components/Header/Header.tsx
  src/components/ItemBox/SwiperItem.tsx
  src/components/SearchResult/SearchFindResult.tsx
  src/components/pages/02-FindItem/GetList.tsx
  src/components/pages/03-LostItem/LostList.tsx
Labels: feature

#178 [코드 수정] (Kim/#176): 상세 검색 결과 페이지 path name 수정 및 스켈레톤 UI 레이아웃 수정
  src/App.tsx
  src/components/SearchResult/SearchFindResult.tsx
  src/components/SearchResult/SearchLostResult.tsx
  src/components/pages/02-FindItem/GetList.tsx
  src/components/pages/03-LostItem/LostList.tsx
  src/main.tsx
Labels: mod

#183 [코드 수정] (Kim/#180): 자유게시판 레이아웃 통일 작업
  src/components/Navigation/Navigation.tsx
  src/components/common/atom/Horizon.tsx
  src/components/pages/05-Community/PostDetail.tsx
  src/components/pages/05-Community/PostList.tsx
  src/components/pages/05-Community/SearchPost.tsx
Labels: mod

#184 [코드수정](jung/#182) 프로필 수정 변경
  src/components/pages/04-MyPage/MypageEdit.tsx
Labels: bugfix

#186 [기능] tanstack query 적용
  src/App.tsx
  src/components/ItemBox/SwiperItem.tsx
  src/components/pages/02-FindItem/GetList.tsx
  src/components/pages/03-LostItem/LostList.tsx
  src/lib/utils/getAPIData.ts
  src/lib/utils/raiseValue.ts
  src/types/types.ts
Labels: feature

#188 [버그 수정] (kim/#187): 모바일 화면에서 캘린더 아이콘 깨지는 현상 해결
  src/components/SearchDetail/molecule/SearchDate.tsx
  src/components/SearchDetail/pages/SearchFindDetail.tsx
  src/tailwind.css
Labels: bugfix

#193 [문서 작성] (kim/#readme): 리드미 작성
  README.md
Labels: doc
